#!/usr/bin/env bash

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"

# Check if the scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully!"
else
    echo "Failed to transfer the file."
    exit 1
fi
