#!/bin/bash

# Check if an argument (IP address) is passed
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    # Ping the given IP address 5 times
    ping -c 5 "$1"
fi
