#!/usr/bin/env bash

# Create a PID file
echo $$ > /var/run/myscript.pid

# Function to handle termination and quit signals
cleanup() {
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap signals
trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'cleanup' SIGQUIT

# Infinite loop displaying a message
while true; do
    echo "To infinity and beyond"
    sleep 2
done
