#!/usr/bin/env bash

PIDFILE=/var/run/my_process.pid

start() {
    echo "Starting manage_my_process..."
    # Start the manage_my_process script in the background
    /usr/local/bin/manage_my_process & echo $! > "$PIDFILE"
    echo "manage_my_process started"
}

stop() {
    echo "Stopping manage_my_process..."
    if [ -f "$PIDFILE" ]; then
        kill "$(cat "$PIDFILE")"
        rm -f "$PIDFILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
